// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package ideas

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Idea struct {
	ID        int64
	Title     pgtype.Text
	Body      pgtype.Text
	CreatedAt pgtype.Timestamp
	DoneAt    pgtype.Timestamp
}
