// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package ideas

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Ideas struct {
	ID        int64            `json:"id"`
	Title     pgtype.Text      `json:"title"`
	Body      pgtype.Text      `json:"body"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	DoneAt    pgtype.Timestamp `json:"done_at"`
}
