// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package ideas

import (
	"context"
)

type Querier interface {
	CreateIdea(ctx context.Context, arg CreateIdeaParams) (CreateIdeaRow, error)
	ListIdeas(ctx context.Context) ([]Ideas, error)
}

var _ Querier = (*Queries)(nil)
