name: Ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.21

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Get dependencies
      run: |
        go mod download
        go install github.com/a-h/templ/cmd/templ@v0.2.543

    - name: Build
      run: go build -v ./...

    # TODO add comment to the pr about no synced templates
    # TODO use makefile to run this
    - name: Gen temple
      run: templ generate && git diff --exit-code

    - name: Test
      run: go test -v ./...
